/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "CdnBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CdnQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CdnRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "DbProperties": {
      "ZERO_CHANGE_DB_NAME": string
      "ZERO_CVR_DB_NAME": string
      "ZERO_UPSTREAM_DB_NAME": string
      "connectionString": string
      "type": "sst.sst.Linkable"
    }
    "DevEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "DevEmailAddress": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DomainEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImageAnalysisApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Urls": {
      "domain": string
      "rootDomain": string
      "type": "sst.sst.Linkable"
    }
    "Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "Zero": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "ZeroDatabase": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}